name : Publish Package
on :
  release :
    types : [ published ]
permissions :
  id-token : write
  contents : read
jobs :
  build :
    runs-on : ubuntu-latest
    steps :
      - uses : actions/checkout@v4
      - run : bash tests/runner.sh

      - uses : actions/setup-node@v4
        with :
          node-version : '24'
          registry-url : 'https://registry.npmjs.org'
      - run : npm run test
      - run : npm publish
