name : Publish Package
on :
  release :
    types : [ published ]
jobs :
  build :
    runs-on : ubuntu-latest
    steps :
      - name : Checkout Repository
        uses : actions/checkout@v4

      - name : Run Bash Tests
        run : bash tests/runner.sh
